### ISSUE TITLE
can't get authorization code

### ISSUE THREAD

**Issue by basesnow** [emmcc/node-switchmate#14]
I am running the latest FW 2.99.18 on TSM001W. I am configuring with a Mac. I can get all the way to running the ./pair.switchmate. It says that it connects and asks me to press the switchmate. I press the button on it, but nothing ever happens. I press it a bunch of times and it eventually tells me that the pairing failed. I can't seem to get an authorization code. Any ideas?

**Comment by kianrafiee** [comment]
I cant even get to where it says to press the switchmate... i just get to "Locating ..."

**Comment by kianrafiee** [comment]
I've since realized its because newer firmwares do not require authorization(pairing) so this script will fail.

**Comment by epheterson** [comment]
Oh I think you might be hitting the same thing as me: https://github.com/emmcc/node-switchmate/issues/15

Turn on debug logging by commenting out the lines in the "pair.switchmate" file you're running to confirm, look at line 42.

Unfortunately I don't know what the fix is.

**Comment by epheterson** [comment]
Actually, I got it working with the node-switchmate3 project, the new firmware doesn't require an authorization code (surprisingly).

**Comment by basesnow** [comment]
I tried using node-switchmate3, but when I go to run the ~/node_modules/node-switchmate3/bin/discover.switchmate3 command, it says that I don't have permissions . . . I can't seem to go any further because of this.

**Comment by epheterson** [comment]
You should take that question to switchmate3 repo. :)

Anyway, I think I had to chmod u+x * in that directory to get the files executable, and maybe try with sudo but I don’t think I had to.

**Comment by epheterson** [comment]
Also, I couldn't get the homebridge-switchmate3 project to work, just node-switchmate3. So once I got the toggle commands working from Terminal, I just used a cmdSwitch2 plugin to run the commands – unfortunately, I never got polling working so I just default it to off.

**Comment by basesnow** [comment]
interesting. I fixed my permissions issue, and I have been playing around with this for a little bit and I am experiencing the same thing with homebridge-switchmate3. Got the node-switchmate3 to toggle. polling just connects, then immediately disconnects. I can toggle manually. Other than that, I can't get it to work.

**Comment by epheterson** [comment]
You described my same experience, yeah. Better than nothing! If you use Siri/scenes/automations, it doesn't matter that polling doesn't work.

**Comment by epheterson** [comment]
Here's my cmdswitch2 setup, if it helps:
```
		"platform": "cmdSwitch2",
		"switches": [
			{
				"name": "Switchmate",
				"on_cmd": "/path/to/node-switchmate3/bin/toggle.switchmate3 xxx on",
				"off_cmd": "/path/to/node-switchmate3/bin/toggle.switchmate3 xxx off",
				"state_cmd": "echo off | grep on",
				"polling": false
			}
		]
```

**Comment by basesnow** [comment]
thanks a lot man, got this up and running now. much appreciated.

**Comment by jeffl78** [comment]
Hey basesnow, how’d you fix your permission issue?  I have the same problem.

**Comment by epheterson** [comment]
Hey Jeff, just read up from the bottom.

**Comment by jeffl78** [comment]
So you talking about some version of the “chmod u+x” command right?  I’m researching that now as coding and computers is something I’m somewhat new to.

**Comment by jeffl78** [comment]
I cannot get the proper permission set up if anyone can help me.
